### ISSUE TITLE
Question: storage

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#50] opened 2018-11-27 19:22 UTC
Are aiohttp sessions closed when created by module itself? If in fact the sessions are not closed we could perhaps add something in line with 
```
    def __del__(self):
        event_loop = asyncio.get_event_loop()
        event_loop.run_until_complete(self._close_session())
   
    async def _close_session(self):
        await self.session.close()
```

**Comment by TheKevJames** [comment] 2018-11-28 02:52
`aiohttp.ClientSession` management has been a sore point for me for a while -- I haven't found a good way to handle this in a library. Its easy enough in an application, since you have full control of everything, but I haven't been able to untangle all the potential usages for a library like `gcloud-aio`.

For example with the code snippet you provided above:
- what if the event loop is still / already running?
- how do we tell the difference between a session provided by the user and not?
- what if `ClientSession.__aexit__` triggers at some point in application code, when the library isn't expecting it?
- Python destructors are not ordered or triggered immediately, as you would need for a RAII pattern like this. `Storage.__del__` may end up being called after `ClientSession.__del__` anyway (or not at all!)

The only way I've come up with the be absolutely sure about all of the above is to use an `async with` for any sessions we create, and assume any created by user's are handled by users.

Ex: (within one of the methods which uses a session):
```
if session:
    resp = await session.post(...)
else:
    async with ClientSession(...) as session:
        resp = await session.post(...)
```
but that comes with a bunch of code re-use and does not re-use sessions, which as I understand is a big no-no in `aiohttp` land.

Any help in grokking how on Earth these sessions are supposed to be used in the `gcloud-aio` / library case would be much appreciated!

**Comment by TheKevJames** [comment] 2018-11-28 19:45
Ah, no, the issue is with `loop.run_until_complete()`, which will throw an error if an event loop is already running. Toy example:
```
>>> import asyncio
>>> async def bar():
...   print('bar')
...
>>> async def foo():
...   loop = asyncio.get_event_loop()
...   loop.run_until_complete(bar())
...   print('foo')
...
>>> asyncio.get_event_loop().run_until_complete(foo())
bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in foo
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 560, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 515, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

What's the motivation behind avoiding creating the sessions (if none are provided) within `gcloud-aio-storage`? They don't necessarily clean up properly, but they do work and allow the library to function. I think I'd be more inclined to print a warning if the library has to create a session, but continue to do so to avoid breaking legacy use-cases.

**Comment by TheKevJames** [comment] 2019-02-15 04:53
Closing this as a duplicate of #33 to consolidate discussion in one place.

**Closed by TheKevJames** 2019-02-15 04:53 UTC
Labels: question
