### ISSUE TITLE
Blob.upload overwrites self.bucket with a string

### ISSUE THREAD

**Issue by p4l1ly** [talkiq/gcloud-aio#262] opened 2020-12-03 09:55 UTC
[This line](https://github.com/talkiq/gcloud-aio/blob/67948064935b592a1e26c3c14039c98be93b7d0a/storage/gcloud/aio/storage/blob.py#L53) overwrites self.bucket with a string (the bucket's name), so the blob is no more usable.

**Comment by TheKevJames** [comment] 2021-11-11 22:38
Entirely correct, we definitely need to consider a redesign of that class to avoid the issue. Closing as a dupe of #47

**Closed by TheKevJames** 2021-11-11 22:38 UTC
